-- DropForeignKey
ALTER TABLE IF EXISTS "AuthToken" DROP CONSTRAINT IF EXISTS "AuthToken_userId_fkey";

-- AddForeignKey
ALTER TABLE IF EXISTS "AuthToken" ADD CONSTRAINT "AuthToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
